version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ifsc-service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL=300
      - DATA_FRESHNESS_DAYS=30
      - RAZORPAY_IFSC_BASE_URL=https://ifsc.razorpay.com
    depends_on:
      - mongodb
      - redis
    networks:
      - ifsc-network
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ifsc-service
    networks:
      - ifsc-network
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ifsc-network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:

networks:
  ifsc-network:
    driver: bridge
